Added edit your profile
Worzaii/Mafiaspill pull request #38
Opened 2021-01-05 17:32 UTC by Mollysaurusen

Added a basic function to edit your profile

2021-01-05 17:49 UTC, Worzaii requested changes
A few tips and guidelines. One commit seem to look exactly alike one other commit. Check reviews.

2021-01-05 17:49 UTC, Worzaii commented on endreprofil.php
> + */
Why is this comment about the crime script here? "Todo"'s are plans on what to do next.

2021-01-05 17:49 UTC, Worzaii commented on endreprofil.php
> +include_once '/classes/MinSide.php';
Why is this class included? Is it used in any way?

2021-01-05 17:49 UTC, Worzaii commented on EndreProfil.php
> +class EndreProfil
Why isn't this extending "mainclass" to inherit used functions such as execute?

2021-01-05 17:49 UTC, Worzaii commented on EndreProfil.php
> +        if ($write = canUseFunction(1, 1)) {
This function will hinder the user from using the function if jailed or bunkered. Either set values to 0 and 0 unless the intention is to not allow changing a profile while either option is active, or simply do "readyEndreProfil" without the if clause.

2021-01-05 17:54 UTC, Mollysaurusen commented on endreprofil.php
> +include_once '/classes/MinSide.php';
> Why is this class included? Is it used in any way?

You can replace it whit

 include_once __DIR__ . '/classes/EndreProfil.php';

2021-03-06 19:07 UTC, Worzaii commented
No reply or changes made, closing request to pull.

2021-03-06 19:07 UTC, closed without merging